import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { InventoryCountProvider } from "@/contexts/StockContext";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Stock Control App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${roboto.variable} antialiased`}>
        <InventoryCountProvider>{children}</InventoryCountProvider>
      </body>
    </html>
  );
}
